#!/bin/sh
(                                                                  \
  grep -E "$(hostname)" /etc/hosts | cut -f1                       \
  &                                                                \
  netstat -tn | grep ESTABLISHED | awk '{print $5}' | cut -d: -f1  \
  | sed -n "/$(echo $SSH_CLIENT | awk '{ print $1 }')/!pg" ;       \
)                                                                  \
| sort -u
